### ISSUE TITLE
Make dataset ready for huggingface

### ISSUE THREAD

**Issue by MrOrz** [cofacts/opendata#23]
- Initialtive: https://g0v.hackmd.io/joEUsABVRr2aMQqD-Z8ixQ#Access-of-open-data
- Action: https://g0v.hackmd.io/hn7Zy2X1QKuM8Kb5K6d4pA#Access-of-open-data
- Advice from the community: https://g0v.hackmd.io/p-4gLJ-ASe-0wzp_G6h7TQ?view Teemo++
- Found fix for the format issue in HuggingFace - https://g0v.hackmd.io/uO2pc1SlQCqtK7WZBknBZw#%E5%8D%94%E4%BD%9C

# TODO
- [x] Fix CSV file line ending
- [x] Add [YAML config](https://huggingface.co/docs/datasets/repository_structure#configurations) Update README: Include the use of [`datafiles`] to stop HF from doing automatic split
- [x] Update README: include [join](https://towardsdatascience.com/left-join-with-pandas-data-frames-in-python-c29c85089ba4)s, outputs results. Scenarios:
    - Topic classification: `articles` + `categories`
    - Predicting crowd label (rumor / not-rumor / opinionated) of a text: articles + article-replies
    - Q&A dataset: articles + article-replies + replies

**Comment by MrOrz** [comment]
All complete and available on https://huggingface.co/datasets/Cofacts/line-msg-fact-check-tw
